export const environment = {
  production: true,
  firebaseConfig : {
    apiKey: "AIzaSyC_vC_cpFkc0ZiCdey9tEx2TMW0bNQzPjM",
    authDomain: "royal-stallion.firebaseapp.com",
    databaseURL: "https://royal-stallion.firebaseio.com",
    projectId: "royal-stallion",
    storageBucket: "royal-stallion.appspot.com",
    messagingSenderId: "296126986485",
    appId: "1:296126986485:web:ea750bc8e8576b16062dbc",
    measurementId: "G-EDH0E6EHS1"
  },
  english_translations:{
    copyright:"2022 © Competitiveness Financial",
    KYC:"KYC",
    Campaign:"Campaign",
    Dashboard:"Dashboard",
    Loan_Management:"Loan Management",
    This_field_is_required:"This field is required",
    Selected_value:"Selected value:",
    APPLY_DATA:"APPLY DATA",
    Apply_Loan:"Apply Loan",
    Borrowers:"Borrowers",
    Investors:"Investors",
    Organizers:"Organizers",
    Due_Date:"Due Date",
    Principle_Amount:"Principle Amount",
    Profit_Amount:"Profit Amount",
    Total_Amount:"Total Amount",
    Investors_Expected_Profit:"Investors Expected Profit",
    Organizers_Expected_Profit:"Organizers Expected Profit",
    Approve:"Approve",
    Reject:"Reject",
    Campaign_Images:"Campaign Images",
    Team:"Team",
    Enter:"Enter",
    Select_Product:"Select Product",
    Reason_for_rejection:"Reason for rejection",
    Reason:"Reason",
    Close:"Close",
    Save_changes:"Save changes",
    Campaign_List:"Campaign List",
    Home:"Home",
    Tagline:"Tagline",
    Minimum_Investment:"Minimum Investment",
    Maximum_Investment:"Maximum Investment",
    Share_price:"Share price",
    Total_Valuation:"Total Valuation",
    Status:"Status",
    Action:"Action",
    Active:"Active",
    Inactive:"Inactive",
    Are_you_sure_you_want_to_delete_this:"Are you sure you want to delete this?",
    Delete:"Delete",
    Cancel:"Cancel",
    Add_Evaluation_Attributes:"Add Evaluation Attributes",
    Evaluation_Name:"Evaluation Name",
    Enter_Your_Evaluation_Name:"Enter Your Evaluation Name",
    Evaluation_Ar_Name:"Evaluation Ar Name",
    Enter_Your_Evaluation_Ar_Name:"Enter Your Evaluation Ar Name",
    Role_Type:"Role Type",
    Rank_Type:"Rank_Type",
    Select_Rank_Type:"Select Rank Type",
    Position:"Position",
    Evaluation_Category_Details:"Evaluation Category Details",
    Enter_Category_Title:"Enter Category Title",
    Enter_Ar_Category_Title:"Enter Ar Category Title",
    Enter_Min_Range:"Enter Min Range",
    Enter_Max_Range:"Enter Max Range",
    Update:"Update",
    Submit:"Submit",
    Back:"Back",
    Create_New:"Create New",
    Add:"Add",
    Evaluation_Attribute_Details:"Evaluation Attribute Details",
    Create_Attribute:"Create Attribute",
    Select_Category:"Select Category",
    Enter_Attribute_Title:"Enter Attribute Title",
    Enter_Ar_Attribute_Title:"Enter Ar Attribute Title",
    TITLE:"TITLE",
    AR_TITLE:"AR TITLE",
    Min:"Min",
    Max:"Max",
    POSITION:"POSITION",
    STATUS:"STATUS",
    Evaluation_List:"Evaluation List",
    Add_KYC:"Add KYC",
    KYC_Name:"KYC Name",
    Enter_Your_KYC_Name:"Enter Your KYC Name",
    KYC_Ar_Name:"KYC Ar Name",
    Enter_Your_KYC_Ar_Name:"Enter Your KYC Ar Name",
    KYC_Details:"KYC Details",
    Enter_KYC_Detail_Title:"Enter KYC Detail Title",
    Enter_Ar_KYC_Detail_Title:"Enter Ar KYC Detail Title",
    Select_Field_Type:"Select Field Type",
    Select_Information_Type:"Select Information Type",
    Add_Info_Type:"Add Info Type",
    Info_Type_Name:"Info Type Name",
    Enter_Your_Info_Type_Name:"Enter Your Info Type Name",
    Info_Type_Ar_Name:"Info Type Ar Name",
    Enter_Your_Info_Type_Ar_Name:"Enter Your Info Type Ar Name",
    Info_Type_List:"Info Type List",
    Yes:"Yes",
    No:"No",
    Tell_about_your:"Tell about your",
    Reject_KYC:"Reject KYC",
    KYC_List:"KYC List",
    Name:"Name",
    Mobile_Number:"Mobile Number",
    Email:"Email",
    Approved:"Approved",
    Rejected:"Rejected",
    Pending:"Pending",
    User_roles:"User Roles",
    Add_Templates:"Add Templates",
    Enter_Title:"Enter Title",
    Enter_Ar_title:"Enter Ar title",
    Subject:"Subject",
    Enter_Subject:"Enter Subject",
    Ar_Subject:"Ar Subject",
    Enter_Ar_Subject:"Enter Ar Subject",
    Template_Type:"Template Type",
    Select_Template_type:"Select Template type",
    Message:"Message",
    Paste_your_HTML_content_here:"Paste your HTML content here...",
    Email_Templates_List:"Email Templates List",
    SMS_Templates_List:"SMS Templates List",
    Create_New_Template:"Create New Template",
    Registration:"Registration",
    Edit:"Edit",
    Product_Attributes:"Product Attributes",
    Product_Attribute_Name:"Product Attribute Name",
    Enter_Your_Product_Attribute_Name:"Enter Your Product Attribute Name",
    Product_Attribute_Ar_Name:"Product Attribute Ar Name",
    Enter_Your_Product_Attribute_Ar_Name:"Enter Your Product Attribute Ar Name",
    Multiselect:"Multiselect",
    Product_Attribute_Details:"Product Attribute Details",
    Enter_Product_Attribute_Detail_Title:"Enter Product Attribute Detail Title",
    Enter_Ar_Product_Attribute_Detail_Title:"Enter Ar Product Attribute Detail Title",
    Enter_Additional_details:"Enter Additional details",
    Enter_Ar_Additional_details:"Enter Additional details",
    Add_Loan:"Add Loan",
    Enter_Your_Title:"Enter Your Title",
    Enter_Your_Ar_Title:"Enter Your Ar Title",
    Product_Category:"Product Category",
    Select_Product_Category:"Select Product Category",
    Opportunities:"Opportunities",
    Select_Opportunity:"Select Opportunity",
    Loan_Type:"Loan Type",
    Select_Loan_Type:"Select Loan Type",
    Add_Interest_Details:"Add Interest Details",
    Interest_Calculation_Method:"Interest Calculation Method",
    Select_Calculation_Method:"Select Calculation Method",
    Accured_Interest_Posting_Frequency:"Accured Interest Posting Frequency",
    Select_posting_frequency:"Select posting frequency",
    How_is_Interest_Rate_charged:"How is Interest Rate charged?",
    Select_Method:"Select Method",
    Interest_Rate_Constrains:"Interest Rate Constrains",
    Default:"Default",
    Enter_Default_Title:"Enter Default Title",
    Fundraiser_Profit:"Fundraiser Profit",
    Enter_Fundraiser_Profit:"Enter Fundraiser Profit",
    Loan_List:"Loan List",
    Add_Payment_Info:"Add Payment Info",
    Payment_Interval_Method:"Payment Interval Method",
    Select_Interval_Method:"Select Interval Method",
    Payments_are_made_every:"Payments are made every",
    Enter_Payment_Period:"Enter Payment Period",
    Select_Payment_Period:"Select Payment Period",
    Installment_Constrains:"Installment Constrains",
    First_Due_date_Offest_Constrains_Days:"First Due date Offest Constrains (Days)",
    Other_Details:"Other Details",
    Collect_Principle_every:"Collect Principle every",
    Enter_Principle:"Enter Principle",
    Repayments:"Repayments",
    Grace_Period_Type:"Grace Period Type",
    Select_Grace_Period_Type:"Select Grace Period Type",
    Grace_Period:"Grace Period",
    Enter_Grace_Period:"Enter Grace Period",
    Product_Attribute_List:"Product Attribute List",
    Produc_List:"Product List",
    Products:"Products",
    Product_Name:"Product Name",
    Enter_Your_Product_Name:"Enter Your Product Name",
    Product_Ar_Name:"Product Ar Name",
    Enter_Your_Product_Ar_Name:"Enter Your Product Ar Name",
    Add_Admin:"Add Admin",
    Enter_Name:"Enter Name",
    Department_Type:"Department Type",
    Select_Department_Type:"Select Department Type",
    Menu:"Menu",
    Role:"Role",
    Enter_Mobile_Number:"Enter Mobile Number",
    Enter_valid_Mobile_Number:"Enter valid Mobile Number",
    Enter_Email:"Enter Email",
    Enter_valid_email_id:"Enter valid email id.",
    Password:"Password",
    Enter_password:"Enter password",
    Password_must_be_characters_or_more:"Password must be 8 characters or more.",
    IP:"IP",
    Enter_Ip:"Enter Ip",
    Admin_IP_List:"Admin IP List",
    Create_New_IP:"Create New IP",
    Created_On:"Created On",
    Admin_IP_Log:"Admin IP Log",
    Users_List:"Users List",
    Create_New_User:"Create New User",
    User_Type:"User Type",
    Department:"Department",
    Sign_In:"Sign In",
    Remember_me:"Remember me",
    Forgot_pwd:"Forgot pwd?",
    Log_In:"Log In",
    Recover_Password:"Recover Password",
    Enter_your_Email_and_instructions_will_be_sent_to_you:"Enter your Email and instructions will be sent to you!",
    Reset:"Reset",
    Logout:"Logout",
    Search:"Search...",
    Info_Type:"Info Type",
    Users_Management:"Users Management",
    Admin_List:"Admin List",
    Opportunity_List:"Opportunity List",
    Notifications:"Notifications",
    Email_Notifications:"Email Notifications",
    SMS_Notifications:"SMS Notifications",
    Please_select_a_product:"Please select a product",
    Please_give_reason_for_rejection:"Please give reason for rejection!",
    updated_successfully:" updated successfully",
    Something_went_wrong_Please_try_again_later:"Something went wrong. Please try again later",
    Evaluation_deleted_successfully:"Evaluation deleted successfully",
    Evaluation_added_successfully:"Evaluation added successfully",
    Attribute_updated_successfully:"Attribute updated successfully",
    KYC_added_successfully:"KYC added successfully",
    KYC_updated_successfully:"KYC updated successfully",
    Info_Type_added_successfully:"Info Type added successfully",
    Info_Type_updated_successfully:"Info Type updated successfully",
    Info_type_deleted_successfully:"Info type deleted successfully",
    KYC_Approved:"KYC Approved",
    KYC_Rejected:"KYC Rejected",
    KYC_deleted_successfully:"KYC deleted successfully",
    User_roles_updated_successfully:"User roles updated successfully.",
    Template_added_successfully:"Template added successfully",
    Template_updated_successfully:"Template updated successfully",
    Attribute_added_successfully:"Attribute added successfully",
    Loan_Details_added_successfully:"Loan Details added successfully",
    Loan_Details_updated_successfully:"Loan Details updated successfully",
    Attribute_deleted_successfully:"Attribute deleted successfully",
    Product_added_successfully:"Product added successfully",
    Product_updated_successfully:"Product updated successfully",
    User_added_successfully:"User added successfully",
    User_updated_successfully:"User updated successfully",
    Ip_added_successfully:"Ip added successfully",
    Login_Successful_Welcome:"Login Successful! Welcome ",
    investor_statement:"investor statement",
    invester_name:"Invester Name",
    invested_amount:"Invested Amount",
    date:"Date",
    Total_Investment:"Total Investment",
    No_Of_Investors:"No. Of Investors",
    Required_Investment:"Required Investment",
    Remaining_Investment:"Remaining Investment",
    interest_rate:"Interest Rate",
    no_of_installments:"No of Installments",
    no_of_days:"No of days",
    Ar_Message:"Ar Message",
    Pages:"Pages",
    description:"DESCRIPTION",
    ar_description:"AR DESCRIPTION",
    enter_description:"Enter Description",
    enter_ar_description:"Enter Ar Description",
    Opportunity_setup:"Opportunity Setup",
    Select_Role:"Select Role",
    Image:"Image",
    Add_image:"Add Image",
    Add_page:"Add Page",
    Registration_Details:"Registration Details",
    Select_User_Type:"Select User Type",
    AR_Image:"AR Image",
    Opportunity_Product:"Opportunity Product",
    Opportunity_Publish:"Opportunity Publish",
    Publish:"Publish",
    Investment_Details:"Investment Details",
    Length:"Length",
    Select_Mandatory:"Select Mandatory",
    Account_Number:"Account Number"


    
  },
  arabic_translations:{},
};
